name: Steven Test Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Hello world"
        
      - name: Show foler and files
        run: pwd && ls -al

      - name: Show Python version
        run: python -V

      - name: Run sample Python file
        run: python ../../src/welcome.py
